language: c
addons:
    apt:
        packages:
            - libapr1-dev
            - libconfuse-dev

before_install:
    - sudo apt-get update -q
    - sudo apt-get install -y libganglia1-dev

install:
    - mkdir m4
    - autoreconf --install

script:
    - ls /usr/include
    - dpkg-query -L libganglia1-dev
    - ./configure --enable-shared --disable-static  CFLAGS="`apr-1-config --cflags --includes` -I`pwd`/monitor-core/include -I`pwd`/monitor-core/lib -I/usr/include"
    - make

